# Generated by Django 5.2.5 on 2025-12-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfkapp2', '0002_main_chat_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_chat',
            name='owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownername', to='kfkapp2.person'),
        ),
    ]
